#version 450
#extension GL_EXT_samplerless_texture_functions : require

layout(local_size_x = 8, local_size_y = 8, local_size_z = 1) in;

layout(set = 0, binding = 16) uniform sampler InputSampler;
layout(set = 0, binding = 32) uniform texture2D InputImage;
layout(set = 0, binding = 48, r8) uniform writeonly image2D OutputImage;

void main()
{
    ivec2 outputCoord = ivec2(gl_GlobalInvocationID.xy);
    ivec2 outputSize = imageSize(OutputImage);
    if (any(greaterThanEqual(outputCoord, outputSize)))
        return;

    vec2 inputSize = vec2(textureSize(InputImage, 0));
    vec2 samplePos = min(vec2(outputCoord * 2) + vec2(1.0), inputSize - vec2(0.5));
    vec2 uv = samplePos / inputSize;
    float luma = textureLod(
        sampler2D(InputImage, InputSampler), uv, 0.0).r;
    imageStore(OutputImage, outputCoord, vec4(luma));
}
